name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.c"
      - "**.cpp"
      - "**.java"
      - "**.py"

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: ğŸ¦… Boramae reviews algorithm
        uses: SukJinKim/Boramae-reviews-algorithm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # "OPENAI", "ANTHROPIC" ë‘˜ ì¤‘ í•˜ë‚˜ ì„ íƒ
          model_company: "ANTHROPIC"
          api_key: ${{ secrets.API_KEY }}
          # Few shot learning ì ìš©ì„ ì›í•˜ì§€ ì•ŠëŠ”ë‹¤ë©´ ì•„ë˜ ì£¼ì„ ì²˜ë¦¬
          few_shot_learning: "true"
